# Generated by Django 6.0.3 on 2026-04-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('flag_code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('stage', models.CharField(choices=[('Group', 'Group Stage'), ('R16', 'Round of 16'), ('QF', 'Quarter-Final'), ('SF', 'Semi-Final'), ('3rd', 'Third Place'), ('Final', 'Final')], default='Group', max_length=10)),
                ('group', models.CharField(blank=True, default='', max_length=1)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('odds_home', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('odds_away', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='backend.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='backend.team')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['kickoff'],
            },
        ),
    ]
