# Generated by Django 6.0.3 on 2026-04-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_team_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='match',
            name='home_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='backend.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='backend.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('Group', 'Group Stage'), ('R32', 'Round of 32'), ('R16', 'Round of 16'), ('QF', 'Quarter-Final'), ('SF', 'Semi-Final'), ('3rd', 'Third Place'), ('Final', 'Final')], default='Group', max_length=10),
        ),
    ]
