# Generated by Django 6.0.3 on 2026-04-30 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_match_away_label_match_home_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('H', 'Home Win'), ('D', 'Draw'), ('A', 'Away Win')], max_length=1)),
                ('amount', models.PositiveIntegerField()),
                ('odds_at_bet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_settled', models.BooleanField(default=False)),
                ('payout', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='backend.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='backend.player')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
    ]
