# Generated by Django 6.0.3 on 2026-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_bet_amount_alter_player_points_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='formation',
            field=models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-2-3-1', '4-2-3-1'), ('3-5-2', '3-5-2'), ('5-3-2', '5-3-2'), ('3-4-3', '3-4-3'), ('5-4-1', '5-4-1'), ('4-1-4-1', '4-1-4-1')], default='4-3-3', max_length=10),
        ),
    ]
