# Generated by Django 6.0.3 on 2026-06-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_add_formations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='odds_at_bet',
        ),
    ]
