# Generated by Django 6.0.3 on 2026-06-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_bet_odds_at_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
