# Generated by Django 6.0.3 on 2026-06-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_bet_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='updated_at',
            new_name='pick_updated_at',
        ),
    ]
