# Generated by Django 6.0.3 on 2026-06-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_updated_at_bet_pick_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
