services:

  db:
    env_file:
      - .env.prod

  backend:
    build:
      target: prod
    env_file:
      - .env.prod
    command: >
      gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.prod

  nginx:
    image: nginx:stable
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      target: prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static:ro
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
