TEAM_NAME_API_TO_DB: dict[str, str] = {
    "Algeria": "Algeriet",
    "Argentina": "Argentina",
    "Australia": "Australien",
    "Austria": "Österrike",
    "Belgium": "Belgien",
    "Bosnia & Herzegovina": "Bosnien och Hercegovina",
    "Brazil": "Brasilien",
    "Canada": "Kanada",
    "Cape Verde": "Kap Verde",
    "Colombia": "Colombia",
    "Croatia": "Kroatien",
    "Curaçao": "Curaçao",
    "Czech Republic": "Tjeckien",
    "DR Congo": "DR Kongo",
    "Ecuador": "Ecuador",
    "Egypt": "Egypten",
    "England": "England",
    "France": "Frankrike",
    "Germany": "Tyskland",
    "Ghana": "Ghana",
    "Haiti": "Haiti",
    "Iran": "Iran",
    "Iraq": "Irak",
    "Ivory Coast": "Elfenbenskusten",
    "Japan": "Japan",
    "Jordan": "Jordanien",
    "Mexico": "Mexiko",
    "Morocco": "Marocko",
    "Netherlands": "Nederländerna",
    "New Zealand": "Nya Zeeland",
    "Norway": "Norge",
    "Panama": "Panama",
    "Paraguay": "Paraguay",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Saudi Arabia": "Saudiarabien",
    "Scotland": "Skottland",
    "Senegal": "Senegal",
    "South Africa": "Sydafrika",
    "South Korea": "Sydkorea",
    "Spain": "Spanien",
    "Sweden": "Sverige",
    "Switzerland": "Schweiz",
    "Tunisia": "Tunisien",
    "Turkey": "Turkiet",
    "Uruguay": "Uruguay",
    "USA": "USA",
    "Uzbekistan": "Uzbekistan",
}
